### ISSUE TITLE
Does TDWG have a web page that contains copyright, licensing, and disclamer statements?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#32]
The previous draft documentation spec said the footer should contain "A reference or link to a document containing the Copyright, Licensing and Disclaimer statements that govern this document. This will usually be the standard one supplied by TDWG".  Does TDWG have this?  If so, where is it?  Should we require the link?  See section 3.2.3.4 of the documentation spec

**Comment by tucotuco** [comment]
For Darwin Core, I just adopted what is on the bottom of
http://www.tdwg.org/.

**Comment by stanblum** [comment]
TDWG probably should have a "standard" Copyright, Licensing and Disclaimer
statement that could be incorporated into any standard.

As the documentation standard task group, I think it's appropriate to
recommend the policy -- content of the statement(s) and when/where it
should appear) -- but we should confer with the infrastructure group about
where and how that should be staged.

I think it would also be appropriate to reconsider the statement (which
I'll dig up and post later) given the shift in attitudes about "open"
source/data/etc.  Is the use of IRI/URI/URL sufficient to give us the
acknowledgement we would like for the use of TDWG standards?

**Comment by tucotuco** [comment]
Maybe followup with Hilmar and Jonathan and DataONE.

**Comment by jar398** [comment]
Something I forgot to bring up before:

Since all contributions are (legally) individual contributions without any
pay or contract involved, copyright is held by the contributors, unless
licensed or transferred.

For this reason most organizations that take contributions, and make
non-vacuous legal statements about them, have some sort agreement with
contributors that lets them make such statements legally.

Here is an extremely mature example:
https://www.apache.org/licenses/icla.txt

Here is another one - much cleaner and probably a better model:
https://www.w3.org/Consortium/Legal/2015/06-invited-expert.html

Of course permission can be granted through less formal processes, but
someone ought to keep a record of such things, in order to protect TDWG and
reassure re-users of the material.

If nothing like this is in place, I would strongly advise against any kind
of boilerplate license.

Open is hard!

**Comment by jar398** [comment]
Re the statement on tdwg.org mentioned above: It says "Copyright 2007 -
Biodiversity Information Standards - TDWG" - now this may be true, since
I'm not privy to what goes on behind the scenes, but it is only true if the
author was hired by TDWG, or has assigned copyright to TDWG. Assignment can
happen verbally, but it has to happen somehow if TDWG wants to say
"Copyright TDWG".  (If the content were only licensed, not assigned, the
copyright notice would have to be written differently, e.g. "Copyright (c)
2016 the authors" or "the contributors".)

**Comment by baskaufs** [comment]
OK, we haven't really made any progress on this issue and Issue #38 (Licensing for Vocabularies).  They are the last two issues blocking the completion of the Documentation Specification.  So I'm punting on this.  In Section 3.2.3.4, I wrote "The copyright statement and licensing terms SHOULD be specified according to current TDWG policy for that type of document. " This puts the responsibility for having such a policy on some entity other than this task group (e.g. the Executive).  Since the policy may change over time, I don't think there is any point in trying to write it into the standard.  If anybody is unhappy about this action, they can bring it up again during the review stage (preferably with a solution included!).
